#!/usr/bin/env bash
# Deployed evidence collector for the prod module.
#
# Proves the whole chain with a *delta*, not a snapshot: it records counters, starts a
# fresh run through the same API path the operator console uses, then re-reads every
# counter. A hop that is merely reachable does not pass; it has to show the new run's
# data. Every hop is checked because every hop has, at least once, looked healthy while
# silently dropping data.
#
#   UI/API -> control-api -> Kafka -> Flink -> ClickHouse -> Superset
#                        \-> OTel  -> Tempo -> Grafana
#
# Usage (from prod/):
#   bash deploy/scripts/collect-evidence.sh [--out FILE] [--iterations N] [--skip-run]
#
# Exit codes: 0 all hops pass, 1 one or more hops failed, 2 preconditions missing.
# Output is written to stdout and to the evidence file, with host paths stripped.
set -uo pipefail

CTX="${CTX:-k3d-agentsim}"
NS_PLATFORM="${NS_PLATFORM:-platform}"
NS_DATA="${NS_DATA:-data}"
NS_OBS="${NS_OBS:-observability}"
OPERATOR_URL="${OPERATOR_URL:-http://operator.localhost:8090}"
EXPERIMENT="${EXPERIMENT:-exp-purchase-v3}"
ITERATIONS="${ITERATIONS:-500}"
EVENTS_TOPIC="${EVENTS_TOPIC:-sim.iteration.events.v1}"
STATS_TOPIC="${STATS_TOPIC:-sim.failure.stats.v1}"

# Demo credentials; every one of these is a placeholder that a real deployment
# overrides from its secret store (see ../../../README.md production configuration).
CH_USER="${CH_USER:-asc}"; CH_PASSWORD="${CH_PASSWORD:-asc}"
SUPERSET_USER="${SUPERSET_USER:-admin}"; SUPERSET_PASSWORD="${SUPERSET_PASSWORD:-admin}"
GRAFANA_USER="${GRAFANA_USER:-admin}"; GRAFANA_PASSWORD="${GRAFANA_PASSWORD:-admin}"

PORT_CH="${PORT_CH:-18123}"; PORT_SUPERSET="${PORT_SUPERSET:-18088}"
PORT_GRAFANA="${PORT_GRAFANA:-13000}"; PORT_FLINK="${PORT_FLINK:-18081}"

OUT=""; SKIP_RUN=0
while [ $# -gt 0 ]; do
  case "$1" in
    --out) OUT="$2"; shift 2 ;;
    --iterations) ITERATIONS="$2"; shift 2 ;;
    --skip-run) SKIP_RUN=1; shift ;;
    -h|--help) sed -n '2,20p' "$0"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done
[ -n "$OUT" ] || OUT="docs/evidence/$(date +%Y-%m-%d)-deployed-evidence.md"

command -v kubectl >/dev/null || { echo "kubectl not on PATH" >&2; exit 2; }
command -v curl    >/dev/null || { echo "curl not on PATH" >&2; exit 2; }
kubectl --context "$CTX" get ns >/dev/null 2>&1 || {
  echo "cluster context '$CTX' unreachable; bring one up with 'make cluster-up'" >&2; exit 2; }

k() { kubectl --context "$CTX" "$@"; }

PF_PIDS=()
cleanup() { for p in "${PF_PIDS[@]:-}"; do kill "$p" 2>/dev/null || true; done; }
trap cleanup EXIT

port_forward() { # ns svc localport remoteport
  k -n "$1" port-forward "svc/$2" "$3:$4" >/dev/null 2>&1 &
  PF_PIDS+=($!)
}

wait_http() { # url tries
  for _ in $(seq 1 "${2:-20}"); do
    code=$(curl -s -m 3 -o /dev/null -w '%{http_code}' "$1" || true)
    [ "$code" != "000" ] && return 0
    sleep 1
  done
  return 1
}

PASS=0; FAIL=0
declare -a LINES
say() { LINES+=("$1"); printf '%s\n' "$1"; }
hop() { # name status detail
  if [ "$2" = "PASS" ]; then PASS=$((PASS+1)); else FAIL=$((FAIL+1)); fi
  say "| $1 | **$2** | $3 |"
}

kafka_pod() { k -n "$NS_DATA" get pod -l app=kafka -o jsonpath='{.items[0].metadata.name}' 2>/dev/null; }
kafka_total() { # topic -> summed end offsets, or empty on failure
  local pod="$1" topic="$2"
  k -n "$NS_DATA" exec "$pod" -- bash -c \
    "/opt/kafka/bin/kafka-get-offsets.sh --bootstrap-server localhost:9092 --topic $topic" 2>/dev/null \
    | awk -F: '{s+=$3} END{if (NR>0) print s}'
}
ch() { curl -s -m 20 -u "$CH_USER:$CH_PASSWORD" --data-binary "$1" "http://127.0.0.1:$PORT_CH/"; }
ch_count() { ch 'SELECT count() FROM default.failure_stats FORMAT TSV' | tr -d '[:space:]'; }

port_forward "$NS_DATA" clickhouse "$PORT_CH" 8123
port_forward "$NS_DATA" superset "$PORT_SUPERSET" 8088
port_forward "$NS_DATA" flink-jobmanager "$PORT_FLINK" 8081
port_forward "$NS_OBS" grafana "$PORT_GRAFANA" 80
sleep 6

STAMP="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
ARCH="$(uname -m)"
say "# Deployed evidence - prod module"
say ""
say "Generated by \`deploy/scripts/collect-evidence.sh\` on $STAMP (host arch: $ARCH,"
say "cluster context: \`$CTX\`). Evidence tier: **simulation**. Each hop is verified by the"
say "change a fresh run produces, not by the presence of old data."
say ""

# ---------------------------------------------------------------- before
KPOD="$(kafka_pod)"
if [ -z "$KPOD" ]; then
  say "> Kafka pod not found in namespace \`$NS_DATA\`; data-plane hops cannot be checked."
fi
EV_BEFORE="$(kafka_total "$KPOD" "$EVENTS_TOPIC")"
ST_BEFORE="$(kafka_total "$KPOD" "$STATS_TOPIC")"
CH_BEFORE="$(ch_count)"
case "$CH_BEFORE" in ''|*[!0-9]*) CH_BEFORE="" ;; esac

# ---------------------------------------------------------------- the run
RUN_UNSAFE=""; RUN_SAFE=""; DEC_UNSAFE=""; DEC_SAFE=""
if [ "$SKIP_RUN" -eq 0 ]; then
  curl -s -m 30 -X POST "$OPERATOR_URL/api/experiments/seed-golden" \
    -H 'content-type: application/json' >/dev/null
  for harness in basic_retry transaction_safety; do
    resp=$(curl -s -m 300 -X POST "$OPERATOR_URL/api/runs" -H 'content-type: application/json' \
      -d "{\"experimentId\":\"$EXPERIMENT\",\"harness\":\"$harness\",\"iterations\":$ITERATIONS}")
    rid=$(printf '%s' "$resp" | sed -n 's/.*"runId":"\([^"]*\)".*/\1/p')
    dec=$(printf '%s' "$resp" | sed -n 's/.*"status":"\([^"]*\)".*/\1/p')
    if [ "$harness" = "basic_retry" ]; then RUN_UNSAFE="$rid"; DEC_UNSAFE="$dec";
    else RUN_SAFE="$rid"; DEC_SAFE="$dec"; fi
  done
  # Flink windows are processing-time; give them room to fire and ClickHouse to consume.
  sleep 45
fi

say "## Golden workflow through the deployed API"
say ""
say "| Run | Harness | Decision | Expected |"
say "|-----|---------|----------|----------|"
say "| \`${RUN_UNSAFE:-n/a}\` | basic_retry (unsafe) | ${DEC_UNSAFE:-n/a} | Blocked |"
say "| \`${RUN_SAFE:-n/a}\` | transaction_safety (safe) | ${DEC_SAFE:-n/a} | Passed |"
say ""
say "## Per-hop verification"
say ""
say "| Hop | Result | Evidence |"
say "|-----|--------|----------|"

# 1. control-api / decisions
if [ "$SKIP_RUN" -eq 1 ]; then
  hop "control-api (golden workflow)" "SKIP" "run skipped (\`--skip-run\`)"
elif [ "$DEC_UNSAFE" = "Blocked" ] && [ "$DEC_SAFE" = "Passed" ]; then
  hop "control-api (golden workflow)" "PASS" "unsafe -> Blocked, safe -> Passed, $ITERATIONS iterations each"
else
  hop "control-api (golden workflow)" "FAIL" "got unsafe=${DEC_UNSAFE:-none}, safe=${DEC_SAFE:-none}; expected Blocked/Passed"
fi

# 2. Kafka iteration events
EV_AFTER="$(kafka_total "$KPOD" "$EVENTS_TOPIC")"
if [ -n "$EV_BEFORE" ] && [ -n "$EV_AFTER" ] && [ "$EV_AFTER" -gt "$EV_BEFORE" ]; then
  hop "Kafka \`$EVENTS_TOPIC\`" "PASS" "offsets $EV_BEFORE -> $EV_AFTER (+$((EV_AFTER-EV_BEFORE)) events)"
elif [ -n "$EV_AFTER" ] && [ "$SKIP_RUN" -eq 1 ]; then
  hop "Kafka \`$EVENTS_TOPIC\`" "SKIP" "offsets at $EV_AFTER (no fresh run to compare)"
else
  hop "Kafka \`$EVENTS_TOPIC\`" "FAIL" "offsets ${EV_BEFORE:-?} -> ${EV_AFTER:-?}; no new events reached the broker"
fi

# 3. Flink job
FLINK_STATE=""; FLINK_NAME=""
if wait_http "http://127.0.0.1:$PORT_FLINK/config" 10; then
  read -r FLINK_STATE FLINK_NAME <<<"$(curl -s -m 15 "http://127.0.0.1:$PORT_FLINK/jobs/overview" \
    | python3 -c "
import json,sys
try: jobs=json.load(sys.stdin).get('jobs',[])
except Exception: jobs=[]
run=[j for j in jobs if j.get('state')=='RUNNING']
print((run[0]['state'], run[0]['name']) if run else ('NONE','-'), end='')
" 2>/dev/null | tr -d "(),'" )"
fi
if [ "$FLINK_STATE" = "RUNNING" ]; then
  hop "Flink failure-stats job" "PASS" "state RUNNING (\`${FLINK_NAME}\`)"
else
  hop "Flink failure-stats job" "FAIL" "no RUNNING job on the session cluster (state: ${FLINK_STATE:-unreachable})"
fi

# 4. Kafka failure stats (Flink output)
ST_AFTER="$(kafka_total "$KPOD" "$STATS_TOPIC")"
if [ -n "$ST_BEFORE" ] && [ -n "$ST_AFTER" ] && [ "$ST_AFTER" -gt "$ST_BEFORE" ]; then
  hop "Kafka \`$STATS_TOPIC\`" "PASS" "offsets $ST_BEFORE -> $ST_AFTER (+$((ST_AFTER-ST_BEFORE)) aggregates)"
elif [ "$SKIP_RUN" -eq 1 ] && [ -n "$ST_AFTER" ]; then
  hop "Kafka \`$STATS_TOPIC\`" "SKIP" "offsets at $ST_AFTER (no fresh run to compare)"
else
  hop "Kafka \`$STATS_TOPIC\`" "FAIL" "offsets ${ST_BEFORE:-?} -> ${ST_AFTER:-?}; Flink produced no windows"
fi

# 5. ClickHouse
CH_AFTER="$(ch_count)"
case "$CH_AFTER" in ''|*[!0-9]*) CH_AFTER="" ;; esac
if [ -n "$CH_BEFORE" ] && [ -n "$CH_AFTER" ] && [ "$CH_AFTER" -gt "$CH_BEFORE" ]; then
  hop "ClickHouse \`failure_stats\`" "PASS" "rows $CH_BEFORE -> $CH_AFTER (+$((CH_AFTER-CH_BEFORE)))"
elif [ "$SKIP_RUN" -eq 1 ] && [ -n "$CH_AFTER" ]; then
  hop "ClickHouse \`failure_stats\`" "SKIP" "$CH_AFTER rows (no fresh run to compare)"
else
  hop "ClickHouse \`failure_stats\`" "FAIL" "rows ${CH_BEFORE:-?} -> ${CH_AFTER:-?}; the Kafka engine did not ingest"
fi

# 6. Superset - the dashboard's own queries, run through its API
SS_TOKEN="$(curl -s -m 20 -X POST "http://127.0.0.1:$PORT_SUPERSET/api/v1/security/login" \
  -H 'Content-Type: application/json' \
  -d "{\"username\":\"$SUPERSET_USER\",\"password\":\"$SUPERSET_PASSWORD\",\"provider\":\"db\",\"refresh\":true}" \
  | python3 -c "import json,sys; print(json.load(sys.stdin).get('access_token',''))" 2>/dev/null)"
SS_OK=0; names=""; chart_count=0; bad=0
if [ -n "$SS_TOKEN" ]; then
  SS_IDS="$(curl -s -m 60 -H "Authorization: Bearer $SS_TOKEN" \
    "http://127.0.0.1:$PORT_SUPERSET/api/v1/chart/?q=(page_size:100)" \
    | python3 -c "import json,sys; print(' '.join(str(c['id']) for c in json.load(sys.stdin)['result']))" 2>/dev/null)"
  for cid in $SS_IDS; do
    chart_count=$((chart_count+1))
    # Every chart must answer with rows. A chart that renders in the browser but cannot be
    # queried through the API is not provisioned - it was hand-built and will not survive a
    # restart, which is exactly the failure this gate exists to catch.
    rc="$(curl -s -m 60 -H "Authorization: Bearer $SS_TOKEN" \
      "http://127.0.0.1:$PORT_SUPERSET/api/v1/chart/$cid/data/" \
      | python3 -c "
import json,sys
try: d=json.load(sys.stdin)
except Exception: print('unreadable'); raise SystemExit
if 'result' not in d: print('no-query-context'); raise SystemExit
r=d['result'][0]
print(r.get('rowcount',0) if r.get('status')=='success' else 'query-'+str(r.get('status')))
" 2>/dev/null)"
    [ -z "$rc" ] && rc="unreachable"
    names="$names chart-$cid:$rc"
    case "$rc" in
      ''|*[!0-9]*) bad=$((bad+1)) ;;
      0) bad=$((bad+1)) ;;
    esac
  done
  [ "$chart_count" -gt 0 ] && [ "$bad" -eq 0 ] && SS_OK=1
fi
if [ "$SS_OK" -eq 1 ]; then
  hop "Superset dashboard" "PASS" "all $chart_count charts return live rows from ClickHouse -$names"
elif [ -z "$SS_TOKEN" ]; then
  hop "Superset dashboard" "FAIL" "could not authenticate to Superset"
elif [ "$chart_count" -eq 0 ]; then
  hop "Superset dashboard" "FAIL" "no charts provisioned; run \`deploy/scripts/import-superset-dashboards.sh\`"
else
  hop "Superset dashboard" "FAIL" "$bad of $chart_count charts failed -$names"
fi

# 7. Grafana -> Tempo
NOW=$(date +%s)
TRACES="$(curl -s -m 45 -u "$GRAFANA_USER:$GRAFANA_PASSWORD" \
  "http://127.0.0.1:$PORT_GRAFANA/api/datasources/proxy/uid/tempo/api/search?tags=service.name%3Dcontrol-api&start=$((NOW-7200))&end=$NOW&limit=20" \
  | python3 -c "import json,sys; print(len(json.load(sys.stdin).get('traces',[])))" 2>/dev/null)"
[ -z "$TRACES" ] && TRACES=0
if [ "$TRACES" -gt 0 ]; then
  hop "Grafana -> Tempo traces" "PASS" "$TRACES control-api traces queryable through the Grafana datasource proxy"
else
  hop "Grafana -> Tempo traces" "FAIL" "no traces returned; note Tempo indexes on block flush, so very recent runs lag"
fi

# 8. Telemetry not silently degraded
EMITTER="$(k -n "$NS_PLATFORM" exec deploy/control-api -- python -c "
import os
b=os.environ.get('KAFKA_BOOTSTRAP')
print('unset' if not b else 'set')
" 2>/dev/null | tr -d '[:space:]')"
if [ "$EMITTER" = "set" ] && [ -n "$EV_AFTER" ] && [ -n "$EV_BEFORE" ] && [ "$EV_AFTER" -gt "$EV_BEFORE" ]; then
  hop "Telemetry not degraded" "PASS" "KAFKA_BOOTSTRAP set and events observed - emitter is live, not a silent no-op"
elif [ "$EMITTER" = "set" ]; then
  hop "Telemetry not degraded" "FAIL" "KAFKA_BOOTSTRAP is set but no events arrived - the emitter fell back silently"
else
  hop "Telemetry not degraded" "FAIL" "KAFKA_BOOTSTRAP is ${EMITTER:-unknown} on control-api"
fi

# ---------------------------------------------------------------- detail
say ""
say "## ClickHouse aggregates (live)"
say ""
say '```'
LINES+=("$(ch 'SELECT failureClassification, count() AS rows, sum(count) AS failures, sum(duplicateTransactionRisk) AS dup FROM default.failure_stats GROUP BY failureClassification ORDER BY failures DESC FORMAT PrettyCompactMonoBlock')")
printf '%s\n' "${LINES[-1]}"
say '```'
say ""
say "## Result"
say ""
say "**$PASS passed, $FAIL failed.**"

# host paths never leave the machine (models lesson L3)
mkdir -p "$(dirname "$OUT")"
printf '%s\n' "${LINES[@]}" \
  | sed -e "s|$PWD|<repo>/prod|g" -e 's|/Users/[^/ ]*|<home>|g' -e 's|/home/[^/ ]*|<home>|g' \
  > "$OUT"
echo ""
echo "evidence written to $OUT"
[ "$FAIL" -eq 0 ] || exit 1
